runtime: php55
api_version: 1

handlers:
# Serve images as static resources.
- url: /(.+\.(gif|png|jpg|css|js))$
  static_files: \1
  upload: .+\.(gif|png|jpg|css|js)$
  application_readable: true
# Serve php scripts.
- url: /.*
  script: index.php
  secure: always
  redirect_http_response_code: 301
